# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xpserver_web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fcm_registration_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
